### ISSUE TITLE
Saving Throws + Skill Proficiencies in Monsters-SRD5.1-CCBY4.0License-TT.json

### ISSUE THREAD

**Issue by JacobLuceno** [Tabyltop/CC-SRD#1]
Awesome work on this! Its all super helpful! 

Just curious - any chance of getting monster saving throw and skill proficiencies added to Monsters-SRD5.1-CCBY4.0License-TT.json?

Thanks!

**Comment by JustinJM76** [comment]
Thanks for your interest in this project!  Pretty sure that'll be straightforward, looks like it was probably an oversight.  I'll take a look.

**Comment by JustinJM76** [comment]
> Awesome work on this! Its all super helpful!
> 
> Just curious - any chance of getting monster saving throw and skill proficiencies added to Monsters-SRD5.1-CCBY4.0License-TT.json?
> 
> Thanks!

This is all set.  Thanks for bringing it to our attention.
